### ISSUE TITLE
shoWithDelay and tapHandler(hide) don't work

### ISSUE THREAD

**Issue by papay0** [icanzilb/SwiftSpinner#26]
Hi,
I try to add a tap handler with a showWithDelay SwiftSpinner but the SwiftSpinner.hide is never called, with the following code : 

SwiftSpinner.showWithDelay(2.0, title: "Connexion \nen cours...").addTapHandler({
            SwiftSpinner.hide()
            }, subtitle: "Tap to hide while connecting! This will affect only the current operation.")

Is it possible to do what I want ?

**Comment by icanzilb** [comment]
Check `ViewController.swift` in the demo app to see how to do that.

**Comment by maa-x** [comment]
I disagree that the delay method you use in the Demo does the same, mostly because calling .hide() before the timeout doesn't cancel the Spinner.

I'd actually submit that there should only be one method, show() with optional parameters for delay and duration. I haven't looked at the code but if need be I wouldn't mind helping out.
