### ISSUE TITLE
How to show on a UITableViewController?

### ISSUE THREAD

**Issue by PickMe** [icanzilb/SwiftSpinner#29]
I can't get it to work....

**Comment by Felix-Weber** [comment]
Do you get any error? Because I just implemented this in a UITableViewController and it works just fine.

**Comment by AndrewAKing** [comment]
Can you show your code & associated error messages? I'm running it on a UITableViewController in the same way you would on any other type.

**Comment by agates4** [comment]
no error and i can confirm it does not work

**Comment by aamck** [comment]
Working for me just fine; can you provide more information / code showing what's going on?

**Comment by DavidLari** [comment]
Works for me as well. Using it in several table view controllers. Calling it from viewWillAppear.

**Comment by agates4** [comment]
import UIKit
import SwiftSpinner

class TestTable: UITableViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        SwiftSpinner.show("Updating History...", animated: true)
    }
    
    override public func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
    }
    
    
}

Causes spinner to show for a few seconds, before abruptly failing

**Comment by agates4** [comment]
[SwiftSpinTest.zip](https://github.com/icanzilb/SwiftSpinner/files/761843/SwiftSpinTest.zip)

**Comment by aamck** [comment]
Yeah the spinner works fine, your problem is that you haven't set the custom class in your storyboard for the tableview itself.

As you can see in the console: a print test in the `viewWillAppear` is an easy way to test if it's actually connected up, let alone supposed to be doing anything.

<img width="1397" alt="screen shot 2017-02-08 at 21 06 26" src="https://cloud.githubusercontent.com/assets/9114246/22757471/d4fefcb6-ee42-11e6-877a-ee3d85b497ab.png">

**Comment by agates4** [comment]
[SwiftSpinTest2.zip](https://github.com/icanzilb/SwiftSpinner/files/762210/SwiftSpinTest2.zip)

sorry, the amended work is here

included is a sidemenu that leads to a tableview with a swift spinner. however, this bug isn't limited to tableviews, but to any view controller as well

**Comment by aamck** [comment]
This is your code: 

``` Swift
class TableViewController: UITableViewController {
    
    @IBOutlet var table: UITableView!
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        print("GOT HERE")
        
        SwiftSpinner.show("test")
     }
}
```

You've made a button called `to table` which when pressed loads a tableView with three cells. When you press the first, it loads a new tableView with the custom class set; running the above code & shows the spinner. The second two cells do nothing because you've not coded in any of the tableview methods.

I feel like this is going in circles and since you're not being at all clear with what you're looking to achieve and the code examples you do provide seem riddled with mistakes or half written examples that don't actually work in the real world _at all_ it's extremely difficult. In both examples you've provided if I fix your code to a bare minimum standard, the spinner works as expected every time.

I **strongly** suggest you spend some time reading about how a `UITablwViewController` works, how to reuse cells and transition between view controllers rather than pasting haphazard code examples claiming that this project is broken, when it clearly is not.

**Comment by agates4** [comment]
[SwiftSpinTest3.zip](https://github.com/icanzilb/SwiftSpinner/files/762244/SwiftSpinTest3.zip)

LOL sorry i attached the wrong project. This is the right one I swear

This one is quite self-explanatory.

**Comment by aamck** [comment]
So what you didn't say is that the `SideMenu` you mentioned is actually another pod all together.

To test my theory, I added this, to `TableViewController.Swift` and the Spinner displayed.

```Swift
	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(true)
		
		let delayInSeconds = 1.0
		DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + delayInSeconds) {
			SwiftSpinner.show("test")
		}
	}
```
_What this means_, is that the spinner is working as intended and something in your `SideMenu` pod is dismissing the `Superview` the Spinner creates itself to run in. So the issue is the interaction between these two pods. Using breakpoints I was able to see that the spinner is presented every time the cell is pressed, but is then instantly dismissed at the end of the transition animation when the 'SideMenu' is dismissed. This is the problem. Once again; `Swiftspinner` is working as intended.

**Comment by agates4** [comment]
thank you very much for your expert debugging skills, I've removed the offending code block and will open a pull request to side menu

motion for close

**Comment by aamck** [comment]
@agates4 You're welcome but in the future don't post such sloppy code examples; take time to proof yourself & your work. More than half the time you'll discover the solution and end up not needing to submit the issue.

Good luck for the project though, hopefully it works out.
