### ISSUE TITLE
Background is not blured correctly

### ISSUE THREAD

**Issue by rweindl** [icanzilb/SwiftSpinner#39]
Hello thank you for providing the SwiftSpinner library! When implementing your library I have a strangely blurred background on the right of the view. The color is slightly different to the rest of the View although the background color is the same 

![simulator screen shot sep 24 2015 8 50 43 pm](https://cloud.githubusercontent.com/assets/2217226/10083334/54b5dadc-62fe-11e5-8030-c014232d9c6d.png)

**Comment by JiriTrecak** [comment]
This is probably because of the background itself - you don't have anything to blur, and single color can do artifacts like that. Usually, in production, this situation is not an issue as there won't be gray background (there is no point in overlaying content with gray and then blur, that's what the blur is for :) ). Try it with normal image background, or normal content, and it will be fine.
