### ISSUE TITLE
shared is unavailable

### ISSUE THREAD

**Issue by Bgimet** [icanzilb/SwiftSpinner#88]
Hello,

Since a "pod update" this morning : 

"Pods/SwiftSpinner/SwiftSpinner/SwiftSpinner.swift:105:49: 'shared' is unavailable: Use view controller based solutions where appropriate instead."

**Comment by icanzilb** [comment]
1) Does the repo DemoApp work for you?
2) Have you googled the exact error message?

**Comment by Bgimet** [comment]
Yes, it appears that the problem is that I want to use it with a Custom Keyboard extension

**Comment by icanzilb** [comment]
if you want to, you still can ... fork SwiftSpinner and change line 105 to `return customSuperview` to clear the error. Then point your Podfile to your own fork (check the CocoaPods website about Podfile syntax if you don't know how). 

Then in your code call `SwiftSpinner.useContainerView(self.view)` to set the container of the spinner (since it won't use the window anymore) 

That all being said - I honestly don't know how it's gonna look in the end, I never tried it in a smaller window like the keyboard extension area. If you do get it to work, post a screenshot here so I can see it
