### ISSUE TITLE
Swift 3 pod file

### ISSUE THREAD

**Issue by RichardBoyder** [icanzilb/SwiftSpinner#92]
Hi guys, the cocoapods is still pointing to 1.1.0 which is not swift 3.

**Comment by Vk12** [comment]
Second this. How can I grab the Swift 3 version?

**Comment by icanzilb** [comment]
Can you elaborate how is it not swift 3? Do you get a particular error message?

**Comment by sealz** [comment]
If you run the converter against the SwiftSpinner target _while converting the project that uses SwiftSpinner_ it suggests a number of changes, for example:

``` swift
public class SwiftSpinner: UIView {
```

becomes:

``` swift
open class SwiftSpinner: UIView {
```

And

``` swift
public class var sharedInstance: SwiftSpinner {
```

becomes:

``` swift
open class var sharedInstance: SwiftSpinner {
```

**Comment by icanzilb** [comment]
Strange, I'm pretty sure the Demo app, included in the repo is swift 3 and that definitely works. Changing a "public" class to an "open" is not incompatibility, though? What happens if you don't run the migrator on the SwiftSpinner target - then it should work just fine?

**Comment by aamck** [comment]
The converter was doing this during the beta to and it makes no difference to functionality, I left them as public in the pull requests I put in because it just seemed more readable as it didn't affect compatibility.
I don't think the converter should be taken at completely face value and its suggestions taken on a case by case basis when applying it to code that doesn't break if the change isn't made.

[This post](http://stackoverflow.com/a/38950955/4969042) on Stack Overflow gives a decent rundown of open vs public. I don't see why open would be useful in this case. @icanzilb will be able to confirm, though.

**Comment by icanzilb** [comment]
I definitely did not intend for this class to be "open", why would the migrator recommend it is beyond me :)

**Comment by RichardBoyder** [comment]
Its working 100%. Swift 3 issue sorted .. 
i don't get any errors or recommendations.  
_____________________________________________
Listen to my music here:
https://itunes.apple.com/za/album/music-of-the-soul/id945963127

Richard Boyder
Skype: richarddeerflame@yahoo.com
